# Generated by Django 5.0.6 on 2024-06-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='eleven/')),
                ('priice', models.IntegerField()),
                ('body', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
